[2025-10-02T20:09:26.548+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_tweets.call manual__2025-10-02T20:09:17.479731+00:00 [queued]>
[2025-10-02T20:09:26.564+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_tweets.call manual__2025-10-02T20:09:17.479731+00:00 [queued]>
[2025-10-02T20:09:26.566+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-02T20:09:26.737+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): call> on 2025-10-02 20:09:17.479731+00:00
[2025-10-02T20:09:26.745+0000] {standard_task_runner.py:57} INFO - Started process 685 to run task
[2025-10-02T20:09:26.750+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_tweets', 'call', 'manual__2025-10-02T20:09:17.479731+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/etl_tweets.py', '--cfg-path', '/tmp/tmpp9xnkeid']
[2025-10-02T20:09:26.753+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask call
[2025-10-02T20:09:26.791+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-02T20:09:26.885+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_tweets.call manual__2025-10-02T20:09:17.479731+00:00 [running]> on host 2024c11e8fc4
[2025-10-02T20:09:27.096+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_tweets' AIRFLOW_CTX_TASK_ID='call' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T20:09:17.479731+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-02T20:09:17.479731+00:00'
[2025-10-02T20:09:27.253+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-10-02T20:09:27.280+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=etl_tweets, task_id=call, execution_date=20251002T200917, start_date=20251002T200926, end_date=20251002T200927
[2025-10-02T20:09:27.341+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-02T20:09:27.391+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
