[2025-10-03T10:49:28.648+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_tweets.call manual__2025-10-03T10:49:17.639000+00:00 [queued]>
[2025-10-03T10:49:28.828+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_tweets.call manual__2025-10-03T10:49:17.639000+00:00 [queued]>
[2025-10-03T10:49:28.829+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-03T10:49:28.863+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): call> on 2025-10-03 10:49:17.639000+00:00
[2025-10-03T10:49:28.875+0000] {standard_task_runner.py:57} INFO - Started process 203 to run task
[2025-10-03T10:49:28.882+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_tweets', 'call', 'manual__2025-10-03T10:49:17.639000+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/etl_tweets.py', '--cfg-path', '/tmp/tmpxrce2m70']
[2025-10-03T10:49:28.887+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask call
[2025-10-03T10:49:28.930+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-03T10:49:29.010+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_tweets.call manual__2025-10-03T10:49:17.639000+00:00 [running]> on host 28c8cb63cdca
[2025-10-03T10:49:29.243+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_tweets' AIRFLOW_CTX_TASK_ID='call' AIRFLOW_CTX_EXECUTION_DATE='2025-10-03T10:49:17.639000+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-03T10:49:17.639000+00:00'
[2025-10-03T10:49:29.387+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-10-03T10:49:29.414+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=etl_tweets, task_id=call, execution_date=20251003T104917, start_date=20251003T104928, end_date=20251003T104929
[2025-10-03T10:49:29.471+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-03T10:49:29.526+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
